name: tests-cygwin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: windows-latest
    env:
      FORCE_COLOR: true
      SHELLOPTS: igncr
      CHERE_INVOKING: true
    strategy:
      fail-fast: false
      matrix:
        python-minor:
          - '9'

    steps:
      - name: Tell git to use proper newlines
        run: git config --global core.autocrlf input

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: 'C:\cygwin'
          key: ${{ runner.os }}-cygwin-python-3${{ matrix.python-minor }}-${{ hashfiles('pyproject.toml') }}

      - name: Setup Cygwin
        uses: cygwin/cygwin-install-action@v2
        with:
          packages: >-
            python3${{ matrix.python-minor }}
            python3${{ matrix.python-minor }}-pip
            cmake make ninja gcc-core gcc-g++ git
            gnupg gnupg2 meson

      - name: Tell Cygwin git about this repository
        # This addresses the "fatal: detected dubious ownership in
        # repository" and "fatal: not in a git directory" errors
        # encountered when trying to run Cygwin git in a directory not
        # owned by the current user. This happens when the tests run
        # Cygwin git in a directory outside the Cygwin filesystem.
        run: git config --global --add safe.directory '*'
        shell: C:\cygwin\bin\env.exe CYGWIN_NOWINPATH=1 CHERE_INVOKING=1 C:\cygwin\bin\bash.exe -leo pipefail -o igncr {0}

      - name: Install nox
        shell: bash.exe -eo pipefail -o igncr "{0}"
        env:
          PATH: "/bin:/usr/bin:/usr/local/bin:/usr/lib/lapack"
          TMP: "/tmp"
          TEMP: "/tmp"
        run: |
            /usr/bin/python -m pip install nox
            nox --version

      - name: Download setuptools/pip wheels for ensurepip
        shell: bash.exe -eo pipefail -o igncr "{0}"
        env:
          PATH: "/bin:/usr/bin:/usr/local/bin:/usr/lib/lapack"
          TMP: "/tmp"
          TEMP: "/tmp"
        run: |
          mkdir -p /usr/share/python-wheels
          /usr/bin/python -m pip wheel --wheel-dir /usr/share/python-wheels setuptools pip wheel

      - name: Run tests
        shell: bash.exe -eo pipefail -o igncr "{0}"
        env:
          PATH: "/bin:/usr/bin:/usr/local/bin:/usr/lib/lapack"
          CHERE_INVOKING: 1
          TMP: "/tmp"
          TEMP: "/tmp"
        run: |
          nox -s test-3.${{ matrix.python-minor }}

      - name: Send coverage report
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        env:
          PYTHON: cygwin-3.${{ matrix.python-minor }}
        with:
          flags: tests
          env_vars: PYTHON
          name: cygwin-3.${{ matrix.python-minor }}
